### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by joelharkes** [monoblaine/gulp-razormin#1]
Dear monoblaine,

i was wondering of the status of this repo. i have been looking for a good razor minifier and i found yours. It seems to be a just a tryout but i'm wondering about the status of your project. Did you make it work? Did you test it with a big razor subset of code?

**Comment by monoblaine** [comment]
Hi!

I'm actively using it in my projects with no problems. The way I minimize the cshtml files is stupidly simple, but I hope that's convenient for you:
1. Temporarily remove the `@using` and `@model` statements,
2. Minimize the rest of the code by removing all the new-line characters and the white-space characters that follow them,
3. Reinsert the `@using` and `@model` statements at the top of the file.

**Possible problems**:
- If there are `<pre>` tags around, this type of minimization will be an unpleasant experience.
- Pre-filled `textarea`s may suffer the same fate.
